[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pemo"
version = "0.0.5"
authors = [
  { name="kenny", email="ztxemail@163.com" },
]
description = "一个帮助用户下载服务器上的文件的命令行工具, 它依托于云存储服务实现中转"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "click==8.1.6",
    "cos-python-sdk-v5==1.9.25",
]

[project.scripts]
pemo = "main:cli"